### ISSUE TITLE
Compilation instructions and clarification on abilities?

### ISSUE THREAD

**Issue by Qiangong2** [jenni/obooks#11]
Two things because the second doesn't warrant its own issue:
1. is it possible for you to write out compilation instructions?
2. Does this work with Oreilly learning (http://learning.oreilly.com/)

**Comment by jenni** [comment]
1. With compilation instructions do you mean steps about how to install it / run it on your computer?
2. Yes, it's for (http://learning.oreilly.com/)

**Comment by Qiangong2** [comment]
1. Yes, install/run on a computer
2. Thanks for clarifying!

**Comment by jenni** [comment]
From the terminal of your computer:

1. clone the project : `$ git clone git@github.com:jenni/obooks.git`
2. cd into the cloned project: `$ cd obooks`
3. install dependencies: `$  npm install`
4. ready to run the command: `$ ./cli -b "9781491952016" -c "long string of cookies here"`

Note that the $ symbol represents the terminal input and should not be typed.
