### ISSUE TITLE
No cookie ID present when logged in with a library card

### ISSUE THREAD

**Issue by Qiangong2** [jenni/obooks#12]
My library provides access to Safari Books online. However, there is no cookie ID present when you log in due to the fact that it is not a personal login. It's a generic volume login that anyone who has a library card in the system can access

**Comment by jenni** [comment]
hi @Qiangong2 I have no idea what deal O'Reilly has with library cards and how it works, I never heard of it before, this library works with paid or trial membership for corporate and personal accounts.

- Can you please provide more information about: 
Do you access O'Reilly through the website (http://learning.oreilly.com/)?
If you see no cookie header, what are the request headers that are sent with each request?

**Comment by Qiangong2** [comment]
Oh, you mentioned that it was for Oreilly | Safari, so I thought it also applied for Safari Books Online.

My library only gives access to Safari Books Online, not Oreilly Learning.

**Comment by jenni** [comment]
Ah, I see, Safari Books Online became O'Reilly at some point, but it seems they still keep the safaribooksonline.com domain for what they call 'classic users', sorry for the confusion! so the answer is no, there's no support for 'classic users' hosted in safaribooksonline.com.

**Comment by Qiangong2** [comment]
Okay, Thanks for the reply! Closing :)
