### ISSUE TITLE
Cookie format example

### ISSUE THREAD

**Issue by vikdean** [jenni/obooks#13]
Hi,
Can you please provide an example how the cookie string should look like? Whatever I do, I'm always getting this:
`(node:6131) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - {"detail":"Authentication credentials were not provided."}
`
Thanks

**Comment by jenni** [comment]
hi @vikdean , it should be the cookie string passed around in the request headers when logged in O'Reilly, which is rather long, like this:
```
return=true; _vwo_uuid_v2=D55F6F8B3A868A9772CA60606B85A3A89|c9e2a33bd6f1e1c903844584ee7cdb2b; _gcl_au=1.1.851824261.1580886569; _ga=GA1.2.1622220399.1580886569; _mkto_trk=id:107-FMS-070&token:_mch-oreilly.com-1580886568718-77255; _fbp=fb.1.1580886568837.164229126; cd_user_id=170142eb26e64e-093effd8ac7bbc-39627c0f-1fa400-170142eb26f40c; _vwo_uuid=DADF65BE961FAEFE01DF76EA1ED0CE3F6; _vwo_ds=3%241580886573%3A15.89870958%3A%3A; _vis_opt_exp_52_combi=1; __qca=P0-817729843-1580886573474; _vis_opt_exp_52_goal_1=1; BrowserCookie=1983064e-9fe1-40fe-886d-7e53ea6d1b42; kampyle_userid=e84c-f4c4-3a1c-a75e-1234-8084-596f-0284; csrfsafari=wu0ZftapIDDY69GnmLfE99wFsI4sSETHsY6f6iBaHICpf0dO4GVEjTEhTD7er8kz; _vis_opt_s=2%7C; _vis_opt_exp_172_combi=1; orm-rt=fb161943df554c879dd43509ececc800; groot_sessionid=yg71warlwgppt7dsz29jjs6xzgop2esn; sessionid=1of4xd9qaony7uro2ttf01lq2cww75u2; reader_preferences=%7B%22font_size%22%3A1%2C%22column_width%22%3A65%2C%22reading_mode%22%3A%22day-mode%22%2C%22zoom_factor%22%3A%7B%22zoom_factor%22%3A2.0189814814814815%7D%7D; recently-viewed=%5B%229781491952016%22%2C%229781449334369%3Ach01.html%22%2C%229781680507287%3Af_0086.xhtml%22%2C%229781491996683%22%2C%229780135165188%22%2C%229781484251393%22%2C%229781786463593%22%2C%229780134663661%22%2C%229781119560012%22%2C%229781491919057%22%5D; _gid=GA1.2.1961618543.1583850253; _gat_UA-112091926-1=1; logged_in=y; orm-jwt=eyJhbGciOiAiUlMyNTYifQ.eyJhY2N0cyI6IFsidsfgrtyertyrtylMDctMTI1YjBjNzM4Yjc3Il0sICJlaWRzIjogeyJoZXJvbiI6ICI2ZjM0Yzc0NC02YjMzLTRkM2EtYmE4NC0yYWI3Mjc3NWQ2NGYifSwgImVudiI6ICJwcm9kdWN0aW9uIiwgImV4cCI6IDE1ODM4NTM4NTYsICJpbmRpdmlkdWFsIjogZmFsc2UsICJwZXJtcyI6IHsiYWNhZG0isddsfmFzaWduIjogInYiLCAiY25mcmMiOiAidiIsICJjcHJleCI6ICJ2IiwgImNzc3RkIjogInYiLCAiZXB1YnMiOiAidiIsICJscnB0aCI6ICJ2IiwgImx2dHJnIjogInYiLCAibnRia3MiOiAidiIsICJvcmlvbCI6ICJ2IiwgInBseWxzIjogInYiLCAic2NucmlvIjogInYiLCAidXNhZ2UiOiAiYyIsICJ1c3JwZiI6ICJldiIsICJ2aWRlbyI6ICJ2In0sICJzdWIiOiAiMGQ4MzhmMjQtMjIzOC00OTIzLTlkMGUtNDkyYzNkZjIxNGQ1In0.oXdnLK4y3LgrwNSgAIAgsdffsdfojf4OALN68V_ODYBCy38Zta_HcEamXIAEsN1YipHKNR7_SRSkR023c3SKfkMjhYJTw--hXjj1D-MnxwjVFzEr7oz9P3KlK1qvfDumFopLL2NOBu_pMdbQ_6gBhFm37SmaowhCIF-4NKqDI; kampyleUserSession=1583850268991; kampyleUserSessionsCount=16; kampyleSessionPageCounter=1
```

So for downloading a book you'd need to do:
`./cli.js -b "12345678" -c "ABOVE COOKIE"`

Also, check if a `session.json` file has been created in the root of the project and delete it if it exists, this file should contain the functional cookies, but if something buggy happened it might be that it saved something wrong and following attempts to download something rely on this particular file.

**Comment by vikdean** [comment]
Hi,
yeah, the problem was that I was using Firefox to copy the string from **Network > Headers > Request Headers > Cookie** and the formatting is different. With Chrome it starts, the download seems to be completed, but the epub generator doesn't seems to work.

```
+:++:++:++:+      using stored cookies...      +:++:++:++:+ 
+:++:++:++:+      Getting:: CCNP and CCIE Security Core SCOR 350-701 Official Cert Guide ...      +:++:++:++:+ 
+:++:++:++:+      26 chapters to download, this can take a while...      +:++:++:++:+ 
..
..
..
(node:2694) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[Success] cover image downloaded successfully!
Zipping temp dir to ....../ccnp-and-ccie-security-core-scor-350-701-official-cert-guide.epub
Done zipping, clearing temp dir...
```

**Comment by jenni** [comment]
@vikdean that looks like a successful download (although the epub lib message is confusing). You should look for this file in your computer `ccnp-and-ccie-security-core-scor-350-701-official-cert-guide.epub` or navigate from the terminal to the folder where the books is -> `cd ~/obooks`.

**Comment by vikdean** [comment]
> @vikdean that looks like a successful download (although the epub lib message is confusing). You should look for this file in your computer `ccnp-and-ccie-security-core-scor-350-701-official-cert-guide.epub` or navigate from the terminal to the folder where the books is -> `cd ~/obooks`.

Yeah, it should be there, but its not...

**Comment by jenni** [comment]
@vikdean I have just downloaded the same book. I've only tested this project on mac. Did the `obooks` folder got created? Which OS are you using?

**Comment by vikdean** [comment]
> @vikdean I have just downloaded the same book. I've only tested this project on mac. Did the `obooks` folder got created? Which OS are you using?

I'm also using macOS. No, no additional folder was created. I've tested it with a different book, same result.

**Comment by jenni** [comment]
Did you clone this repository and ran `$ ./cli -b ...` or did you install the library using npm and ran `$ obooks -b...`? 
Just trying to figure out if the `obooks` folder is created in the right place. 
It is for sure somewhere in your computer otherwise the script would error out - have you tried global search with mac?

**Comment by vikdean** [comment]
> Did you clone this repository and ran `$ ./cli -b ...` or did you install the library using npm and ran `$ obooks -b...`?
> Just trying to figure out if the `obooks` folder is created in the right place.
> It is for sure somewhere in your computer otherwise the script would error out - have you tried global search with mac?

I've edited my entry while you've been writing this I assume.
But yes, the git clone folder name is the same as the export folder name, so thats why I haven't noticed the difference.

**Comment by jenni** [comment]
@vikdean nice, happy reading!
