### ISSUE TITLE
Cover is not properly saved

### ISSUE THREAD

**Issue by tillepille** [jenni/obooks#31]
When downloading a book the log says `[Success] cover image downloaded successfully!` but the final file shows no cover. At least not on my iOS or MacOS apps (Finder, Books).
I also tried an app called PocketBook Reader but it also did not show a cover.

I usually use the provided docker container.

**Comment by jenni** [comment]
@tillepille the cover image assembly is flaky... I've noticed this myself but ignored it.. :)

I'm marking this as a bug. Thanks for reporting it.
